name: Mirror to GitLab

on:
  push:
    branches:
      - dev

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Mirror push to GitLab
        run: |
          git config --global user.name "GitHub Mirror Bot"
          git config --global user.email "mirror@github-actions"
          
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_ICAMS_TOKEN }}@gitlab.com/atomicclusterexpansion/structoscope.git
          git push --mirror gitlab
